export enum AIIntent {
  PROCESS_SEARCH = 'PROCESS_SEARCH',
  PROCESS_DETAILS = 'PROCESS_DETAILS',
  PROCESS_HEALTH = 'PROCESS_HEALTH',
  PROCESS_RISK = 'PROCESS_RISK',
  PROCESS_SUMMARY = 'PROCESS_SUMMARY',
  PROCESS_CRITICAL_LIST = 'PROCESS_CRITICAL_LIST',
  PROCESS_LOW_HEALTH_LIST = 'PROCESS_LOW_HEALTH_LIST',
  PROCESS_HEALTH_AND_RISK = 'PROCESS_HEALTH_AND_RISK',
  CONVERSATION_HELP = 'CONVERSATION_HELP',
  UNKNOWN = 'UNKNOWN'
}

export interface IntentClassification {
  intent: AIIntent;
  confidence: number;
  entities: Record<string, any>;
}
