/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VesselsRouteImport } from './routes/vessels'
import { Route as SystemMonitorRouteImport } from './routes/system-monitor'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesCenterRouteImport } from './routes/sales-center'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PerformanceCenterRouteImport } from './routes/performance-center'
import { Route as OperationsCenterRouteImport } from './routes/operations-center'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OcrReviewCenterRouteImport } from './routes/ocr-review-center'
import { Route as OcrCenterRouteImport } from './routes/ocr-center'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GettingStartedRouteImport } from './routes/getting-started'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DocumentGeneratorRouteImport } from './routes/document-generator'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DebugAuthPublicRouteImport } from './routes/debug-auth-public'
import { Route as DashboardV2RouteImport } from './routes/dashboard-v2'
import { Route as DashboardSafeRouteImport } from './routes/dashboard-safe'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ClientPortalRouteImport } from './routes/client-portal'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AutomationCenterRouteImport } from './routes/automation-center'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as AuthDebugPublicRouteImport } from './routes/auth-debug-public'
import { Route as AuthDebugRouteImport } from './routes/auth-debug'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiCenterRouteImport } from './routes/ai-center'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProcessesIdRouteImport } from './routes/processes.$id'
import { Route as DebugSystemRouteImport } from './routes/debug.system'
import { Route as DebugAuthRouteImport } from './routes/debug.auth'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as DashboardEcosystemRouteImport } from './routes/dashboard.ecosystem'
import { Route as DashboardDocumentsBaseRouteImport } from './routes/dashboard/documents-base'
import { Route as DashboardDocumentCenterRouteImport } from './routes/dashboard.document-center'
import { Route as DashboardDeadlinesRouteImport } from './routes/dashboard.deadlines'
import { Route as DashboardComplianceCenterRouteImport } from './routes/dashboard/compliance-center'
import { Route as BillingSuccessRouteImport } from './routes/billing.success'
import { Route as BillingSubscriptionRouteImport } from './routes/billing.subscription'
import { Route as BillingFailureRouteImport } from './routes/billing.failure'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AnalyticsOperationsRouteImport } from './routes/analytics.operations'
import { Route as AnalyticsOcrRouteImport } from './routes/analytics.ocr'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSystemReportRouteImport } from './routes/admin/system-report'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminStorageRouteImport } from './routes/admin/storage'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminSaasMetricsRouteImport } from './routes/admin/saas-metrics'
import { Route as AdminRoadmapRouteImport } from './routes/admin/roadmap'
import { Route as AdminOperationalFeedbackRouteImport } from './routes/admin/operational-feedback'
import { Route as AdminOcrRouteImport } from './routes/admin/ocr'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminGlobalRouteImport } from './routes/admin/global'
import { Route as AdminFullQaReportRouteImport } from './routes/admin/full-qa-report'
import { Route as AdminFrontendErrorsRouteImport } from './routes/admin/frontend-errors'
import { Route as AdminFieldValidationReportRouteImport } from './routes/admin/field-validation-report'
import { Route as AdminExecutiveOverviewRouteImport } from './routes/admin/executive-overview'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminDocumentLibraryRouteImport } from './routes/admin/document-library'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as AdminCommercialRouteImport } from './routes/admin/commercial'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as AdminAutomationRouteImport } from './routes/admin/automation'

const VesselsRoute = VesselsRouteImport.update({
  id: '/vessels',
  path: '/vessels',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemMonitorRoute = SystemMonitorRouteImport.update({
  id: '/system-monitor',
  path: '/system-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCenterRoute = SalesCenterRouteImport.update({
  id: '/sales-center',
  path: '/sales-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceCenterRoute = PerformanceCenterRouteImport.update({
  id: '/performance-center',
  path: '/performance-center',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsCenterRoute = OperationsCenterRouteImport.update({
  id: '/operations-center',
  path: '/operations-center',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrReviewCenterRoute = OcrReviewCenterRouteImport.update({
  id: '/ocr-review-center',
  path: '/ocr-review-center',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrCenterRoute = OcrCenterRouteImport.update({
  id: '/ocr-center',
  path: '/ocr-center',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedRoute = GettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentGeneratorRoute = DocumentGeneratorRouteImport.update({
  id: '/document-generator',
  path: '/document-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugAuthPublicRoute = DebugAuthPublicRouteImport.update({
  id: '/debug-auth-public',
  path: '/debug-auth-public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardV2Route = DashboardV2RouteImport.update({
  id: '/dashboard-v2',
  path: '/dashboard-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSafeRoute = DashboardSafeRouteImport.update({
  id: '/dashboard-safe',
  path: '/dashboard-safe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPortalRoute = ClientPortalRouteImport.update({
  id: '/client-portal',
  path: '/client-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationCenterRoute = AutomationCenterRouteImport.update({
  id: '/automation-center',
  path: '/automation-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDebugPublicRoute = AuthDebugPublicRouteImport.update({
  id: '/auth-debug-public',
  path: '/auth-debug-public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDebugRoute = AuthDebugRouteImport.update({
  id: '/auth-debug',
  path: '/auth-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCenterRoute = AiCenterRouteImport.update({
  id: '/ai-center',
  path: '/ai-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProcessesIdRoute = ProcessesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProcessesRoute,
} as any)
const DebugSystemRoute = DebugSystemRouteImport.update({
  id: '/debug/system',
  path: '/debug/system',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugAuthRoute = DebugAuthRouteImport.update({
  id: '/debug/auth',
  path: '/debug/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEcosystemRoute = DashboardEcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsBaseRoute = DashboardDocumentsBaseRouteImport.update({
  id: '/documents-base',
  path: '/documents-base',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentCenterRoute = DashboardDocumentCenterRouteImport.update({
  id: '/document-center',
  path: '/document-center',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeadlinesRoute = DashboardDeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplianceCenterRoute =
  DashboardComplianceCenterRouteImport.update({
    id: '/compliance-center',
    path: '/compliance-center',
    getParentRoute: () => DashboardRoute,
  } as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSubscriptionRoute = BillingSubscriptionRouteImport.update({
  id: '/billing/subscription',
  path: '/billing/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingFailureRoute = BillingFailureRouteImport.update({
  id: '/billing/failure',
  path: '/billing/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsOperationsRoute = AnalyticsOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsOcrRoute = AnalyticsOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemReportRoute = AdminSystemReportRouteImport.update({
  id: '/system-report',
  path: '/system-report',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStorageRoute = AdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSaasMetricsRoute = AdminSaasMetricsRouteImport.update({
  id: '/saas-metrics',
  path: '/saas-metrics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoadmapRoute = AdminRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationalFeedbackRoute =
  AdminOperationalFeedbackRouteImport.update({
    id: '/operational-feedback',
    path: '/operational-feedback',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOcrRoute = AdminOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGlobalRoute = AdminGlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFullQaReportRoute = AdminFullQaReportRouteImport.update({
  id: '/full-qa-report',
  path: '/full-qa-report',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFrontendErrorsRoute = AdminFrontendErrorsRouteImport.update({
  id: '/frontend-errors',
  path: '/frontend-errors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFieldValidationReportRoute =
  AdminFieldValidationReportRouteImport.update({
    id: '/field-validation-report',
    path: '/field-validation-report',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminExecutiveOverviewRoute = AdminExecutiveOverviewRouteImport.update({
  id: '/executive-overview',
  path: '/executive-overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentLibraryRoute = AdminDocumentLibraryRouteImport.update({
  id: '/document-library',
  path: '/document-library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommercialRoute = AdminCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomationRoute = AdminAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-center': typeof AiCenterRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/auth-debug': typeof AuthDebugRoute
  '/auth-debug-public': typeof AuthDebugPublicRoute
  '/automation': typeof AutomationRoute
  '/automation-center': typeof AutomationCenterRoute
  '/calendar': typeof CalendarRoute
  '/changelog': typeof ChangelogRoute
  '/client-portal': typeof ClientPortalRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard-safe': typeof DashboardSafeRoute
  '/dashboard-v2': typeof DashboardV2Route
  '/debug-auth-public': typeof DebugAuthPublicRoute
  '/demo': typeof DemoRoute
  '/document-generator': typeof DocumentGeneratorRoute
  '/documents': typeof DocumentsRoute
  '/getting-started': typeof GettingStartedRoute
  '/home': typeof HomeRoute
  '/logs': typeof LogsRoute
  '/ocr-center': typeof OcrCenterRoute
  '/ocr-review-center': typeof OcrReviewCenterRoute
  '/onboarding': typeof OnboardingRoute
  '/operations-center': typeof OperationsCenterRoute
  '/performance-center': typeof PerformanceCenterRoute
  '/plans': typeof PlansRoute
  '/processes': typeof ProcessesRouteWithChildren
  '/sales-center': typeof SalesCenterRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/vessels': typeof VesselsRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/commercial': typeof AdminCommercialRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/document-library': typeof AdminDocumentLibraryRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/executive-overview': typeof AdminExecutiveOverviewRoute
  '/admin/field-validation-report': typeof AdminFieldValidationReportRoute
  '/admin/frontend-errors': typeof AdminFrontendErrorsRoute
  '/admin/full-qa-report': typeof AdminFullQaReportRoute
  '/admin/global': typeof AdminGlobalRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/ocr': typeof AdminOcrRoute
  '/admin/operational-feedback': typeof AdminOperationalFeedbackRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/admin/saas-metrics': typeof AdminSaasMetricsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-report': typeof AdminSystemReportRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/ocr': typeof AnalyticsOcrRoute
  '/analytics/operations': typeof AnalyticsOperationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/billing/failure': typeof BillingFailureRoute
  '/billing/subscription': typeof BillingSubscriptionRoute
  '/billing/success': typeof BillingSuccessRoute
  '/dashboard/compliance-center': typeof DashboardComplianceCenterRoute
  '/dashboard/deadlines': typeof DashboardDeadlinesRoute
  '/dashboard/document-center': typeof DashboardDocumentCenterRoute
  '/dashboard/documents-base': typeof DashboardDocumentsBaseRoute
  '/dashboard/ecosystem': typeof DashboardEcosystemRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/debug/auth': typeof DebugAuthRoute
  '/debug/system': typeof DebugSystemRoute
  '/processes/$id': typeof ProcessesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-center': typeof AiCenterRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/auth-debug': typeof AuthDebugRoute
  '/auth-debug-public': typeof AuthDebugPublicRoute
  '/automation': typeof AutomationRoute
  '/automation-center': typeof AutomationCenterRoute
  '/calendar': typeof CalendarRoute
  '/changelog': typeof ChangelogRoute
  '/client-portal': typeof ClientPortalRoute
  '/customers': typeof CustomersRoute
  '/dashboard-safe': typeof DashboardSafeRoute
  '/dashboard-v2': typeof DashboardV2Route
  '/debug-auth-public': typeof DebugAuthPublicRoute
  '/demo': typeof DemoRoute
  '/document-generator': typeof DocumentGeneratorRoute
  '/documents': typeof DocumentsRoute
  '/getting-started': typeof GettingStartedRoute
  '/home': typeof HomeRoute
  '/logs': typeof LogsRoute
  '/ocr-center': typeof OcrCenterRoute
  '/ocr-review-center': typeof OcrReviewCenterRoute
  '/onboarding': typeof OnboardingRoute
  '/operations-center': typeof OperationsCenterRoute
  '/performance-center': typeof PerformanceCenterRoute
  '/plans': typeof PlansRoute
  '/processes': typeof ProcessesRouteWithChildren
  '/sales-center': typeof SalesCenterRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/vessels': typeof VesselsRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/commercial': typeof AdminCommercialRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/document-library': typeof AdminDocumentLibraryRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/executive-overview': typeof AdminExecutiveOverviewRoute
  '/admin/field-validation-report': typeof AdminFieldValidationReportRoute
  '/admin/frontend-errors': typeof AdminFrontendErrorsRoute
  '/admin/full-qa-report': typeof AdminFullQaReportRoute
  '/admin/global': typeof AdminGlobalRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/ocr': typeof AdminOcrRoute
  '/admin/operational-feedback': typeof AdminOperationalFeedbackRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/admin/saas-metrics': typeof AdminSaasMetricsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-report': typeof AdminSystemReportRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/ocr': typeof AnalyticsOcrRoute
  '/analytics/operations': typeof AnalyticsOperationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/billing/failure': typeof BillingFailureRoute
  '/billing/subscription': typeof BillingSubscriptionRoute
  '/billing/success': typeof BillingSuccessRoute
  '/dashboard/compliance-center': typeof DashboardComplianceCenterRoute
  '/dashboard/deadlines': typeof DashboardDeadlinesRoute
  '/dashboard/document-center': typeof DashboardDocumentCenterRoute
  '/dashboard/documents-base': typeof DashboardDocumentsBaseRoute
  '/dashboard/ecosystem': typeof DashboardEcosystemRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/debug/auth': typeof DebugAuthRoute
  '/debug/system': typeof DebugSystemRoute
  '/processes/$id': typeof ProcessesIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-center': typeof AiCenterRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/auth-debug': typeof AuthDebugRoute
  '/auth-debug-public': typeof AuthDebugPublicRoute
  '/automation': typeof AutomationRoute
  '/automation-center': typeof AutomationCenterRoute
  '/calendar': typeof CalendarRoute
  '/changelog': typeof ChangelogRoute
  '/client-portal': typeof ClientPortalRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard-safe': typeof DashboardSafeRoute
  '/dashboard-v2': typeof DashboardV2Route
  '/debug-auth-public': typeof DebugAuthPublicRoute
  '/demo': typeof DemoRoute
  '/document-generator': typeof DocumentGeneratorRoute
  '/documents': typeof DocumentsRoute
  '/getting-started': typeof GettingStartedRoute
  '/home': typeof HomeRoute
  '/logs': typeof LogsRoute
  '/ocr-center': typeof OcrCenterRoute
  '/ocr-review-center': typeof OcrReviewCenterRoute
  '/onboarding': typeof OnboardingRoute
  '/operations-center': typeof OperationsCenterRoute
  '/performance-center': typeof PerformanceCenterRoute
  '/plans': typeof PlansRoute
  '/processes': typeof ProcessesRouteWithChildren
  '/sales-center': typeof SalesCenterRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/vessels': typeof VesselsRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/commercial': typeof AdminCommercialRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/document-library': typeof AdminDocumentLibraryRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/executive-overview': typeof AdminExecutiveOverviewRoute
  '/admin/field-validation-report': typeof AdminFieldValidationReportRoute
  '/admin/frontend-errors': typeof AdminFrontendErrorsRoute
  '/admin/full-qa-report': typeof AdminFullQaReportRoute
  '/admin/global': typeof AdminGlobalRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/ocr': typeof AdminOcrRoute
  '/admin/operational-feedback': typeof AdminOperationalFeedbackRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/admin/saas-metrics': typeof AdminSaasMetricsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-report': typeof AdminSystemReportRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/ocr': typeof AnalyticsOcrRoute
  '/analytics/operations': typeof AnalyticsOperationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/billing/failure': typeof BillingFailureRoute
  '/billing/subscription': typeof BillingSubscriptionRoute
  '/billing/success': typeof BillingSuccessRoute
  '/dashboard/compliance-center': typeof DashboardComplianceCenterRoute
  '/dashboard/deadlines': typeof DashboardDeadlinesRoute
  '/dashboard/document-center': typeof DashboardDocumentCenterRoute
  '/dashboard/documents-base': typeof DashboardDocumentsBaseRoute
  '/dashboard/ecosystem': typeof DashboardEcosystemRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/debug/auth': typeof DebugAuthRoute
  '/debug/system': typeof DebugSystemRoute
  '/processes/$id': typeof ProcessesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-center'
    | '/analytics'
    | '/auth-debug'
    | '/auth-debug-public'
    | '/automation'
    | '/automation-center'
    | '/calendar'
    | '/changelog'
    | '/client-portal'
    | '/customers'
    | '/dashboard'
    | '/dashboard-safe'
    | '/dashboard-v2'
    | '/debug-auth-public'
    | '/demo'
    | '/document-generator'
    | '/documents'
    | '/getting-started'
    | '/home'
    | '/logs'
    | '/ocr-center'
    | '/ocr-review-center'
    | '/onboarding'
    | '/operations-center'
    | '/performance-center'
    | '/plans'
    | '/processes'
    | '/sales-center'
    | '/settings'
    | '/status'
    | '/support'
    | '/system-monitor'
    | '/vessels'
    | '/admin/automation'
    | '/admin/billing'
    | '/admin/commercial'
    | '/admin/companies'
    | '/admin/document-library'
    | '/admin/documents'
    | '/admin/executive-overview'
    | '/admin/field-validation-report'
    | '/admin/frontend-errors'
    | '/admin/full-qa-report'
    | '/admin/global'
    | '/admin/logs'
    | '/admin/ocr'
    | '/admin/operational-feedback'
    | '/admin/roadmap'
    | '/admin/saas-metrics'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/support'
    | '/admin/system-report'
    | '/admin/users'
    | '/analytics/ocr'
    | '/analytics/operations'
    | '/auth/login'
    | '/auth/signup'
    | '/billing/failure'
    | '/billing/subscription'
    | '/billing/success'
    | '/dashboard/compliance-center'
    | '/dashboard/deadlines'
    | '/dashboard/document-center'
    | '/dashboard/documents-base'
    | '/dashboard/ecosystem'
    | '/dashboard/security'
    | '/debug/auth'
    | '/debug/system'
    | '/processes/$id'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-center'
    | '/analytics'
    | '/auth-debug'
    | '/auth-debug-public'
    | '/automation'
    | '/automation-center'
    | '/calendar'
    | '/changelog'
    | '/client-portal'
    | '/customers'
    | '/dashboard-safe'
    | '/dashboard-v2'
    | '/debug-auth-public'
    | '/demo'
    | '/document-generator'
    | '/documents'
    | '/getting-started'
    | '/home'
    | '/logs'
    | '/ocr-center'
    | '/ocr-review-center'
    | '/onboarding'
    | '/operations-center'
    | '/performance-center'
    | '/plans'
    | '/processes'
    | '/sales-center'
    | '/settings'
    | '/status'
    | '/support'
    | '/system-monitor'
    | '/vessels'
    | '/admin/automation'
    | '/admin/billing'
    | '/admin/commercial'
    | '/admin/companies'
    | '/admin/document-library'
    | '/admin/documents'
    | '/admin/executive-overview'
    | '/admin/field-validation-report'
    | '/admin/frontend-errors'
    | '/admin/full-qa-report'
    | '/admin/global'
    | '/admin/logs'
    | '/admin/ocr'
    | '/admin/operational-feedback'
    | '/admin/roadmap'
    | '/admin/saas-metrics'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/support'
    | '/admin/system-report'
    | '/admin/users'
    | '/analytics/ocr'
    | '/analytics/operations'
    | '/auth/login'
    | '/auth/signup'
    | '/billing/failure'
    | '/billing/subscription'
    | '/billing/success'
    | '/dashboard/compliance-center'
    | '/dashboard/deadlines'
    | '/dashboard/document-center'
    | '/dashboard/documents-base'
    | '/dashboard/ecosystem'
    | '/dashboard/security'
    | '/debug/auth'
    | '/debug/system'
    | '/processes/$id'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-center'
    | '/analytics'
    | '/auth-debug'
    | '/auth-debug-public'
    | '/automation'
    | '/automation-center'
    | '/calendar'
    | '/changelog'
    | '/client-portal'
    | '/customers'
    | '/dashboard'
    | '/dashboard-safe'
    | '/dashboard-v2'
    | '/debug-auth-public'
    | '/demo'
    | '/document-generator'
    | '/documents'
    | '/getting-started'
    | '/home'
    | '/logs'
    | '/ocr-center'
    | '/ocr-review-center'
    | '/onboarding'
    | '/operations-center'
    | '/performance-center'
    | '/plans'
    | '/processes'
    | '/sales-center'
    | '/settings'
    | '/status'
    | '/support'
    | '/system-monitor'
    | '/vessels'
    | '/admin/automation'
    | '/admin/billing'
    | '/admin/commercial'
    | '/admin/companies'
    | '/admin/document-library'
    | '/admin/documents'
    | '/admin/executive-overview'
    | '/admin/field-validation-report'
    | '/admin/frontend-errors'
    | '/admin/full-qa-report'
    | '/admin/global'
    | '/admin/logs'
    | '/admin/ocr'
    | '/admin/operational-feedback'
    | '/admin/roadmap'
    | '/admin/saas-metrics'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/support'
    | '/admin/system-report'
    | '/admin/users'
    | '/analytics/ocr'
    | '/analytics/operations'
    | '/auth/login'
    | '/auth/signup'
    | '/billing/failure'
    | '/billing/subscription'
    | '/billing/success'
    | '/dashboard/compliance-center'
    | '/dashboard/deadlines'
    | '/dashboard/document-center'
    | '/dashboard/documents-base'
    | '/dashboard/ecosystem'
    | '/dashboard/security'
    | '/debug/auth'
    | '/debug/system'
    | '/processes/$id'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiCenterRoute: typeof AiCenterRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  AuthDebugRoute: typeof AuthDebugRoute
  AuthDebugPublicRoute: typeof AuthDebugPublicRoute
  AutomationRoute: typeof AutomationRoute
  AutomationCenterRoute: typeof AutomationCenterRoute
  CalendarRoute: typeof CalendarRoute
  ChangelogRoute: typeof ChangelogRoute
  ClientPortalRoute: typeof ClientPortalRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DashboardSafeRoute: typeof DashboardSafeRoute
  DashboardV2Route: typeof DashboardV2Route
  DebugAuthPublicRoute: typeof DebugAuthPublicRoute
  DemoRoute: typeof DemoRoute
  DocumentGeneratorRoute: typeof DocumentGeneratorRoute
  DocumentsRoute: typeof DocumentsRoute
  GettingStartedRoute: typeof GettingStartedRoute
  HomeRoute: typeof HomeRoute
  LogsRoute: typeof LogsRoute
  OcrCenterRoute: typeof OcrCenterRoute
  OcrReviewCenterRoute: typeof OcrReviewCenterRoute
  OnboardingRoute: typeof OnboardingRoute
  OperationsCenterRoute: typeof OperationsCenterRoute
  PerformanceCenterRoute: typeof PerformanceCenterRoute
  PlansRoute: typeof PlansRoute
  ProcessesRoute: typeof ProcessesRouteWithChildren
  SalesCenterRoute: typeof SalesCenterRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  SupportRoute: typeof SupportRoute
  SystemMonitorRoute: typeof SystemMonitorRoute
  VesselsRoute: typeof VesselsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BillingFailureRoute: typeof BillingFailureRoute
  BillingSubscriptionRoute: typeof BillingSubscriptionRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  DebugAuthRoute: typeof DebugAuthRoute
  DebugSystemRoute: typeof DebugSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vessels': {
      id: '/vessels'
      path: '/vessels'
      fullPath: '/vessels'
      preLoaderRoute: typeof VesselsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-monitor': {
      id: '/system-monitor'
      path: '/system-monitor'
      fullPath: '/system-monitor'
      preLoaderRoute: typeof SystemMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-center': {
      id: '/sales-center'
      path: '/sales-center'
      fullPath: '/sales-center'
      preLoaderRoute: typeof SalesCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance-center': {
      id: '/performance-center'
      path: '/performance-center'
      fullPath: '/performance-center'
      preLoaderRoute: typeof PerformanceCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations-center': {
      id: '/operations-center'
      path: '/operations-center'
      fullPath: '/operations-center'
      preLoaderRoute: typeof OperationsCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr-review-center': {
      id: '/ocr-review-center'
      path: '/ocr-review-center'
      fullPath: '/ocr-review-center'
      preLoaderRoute: typeof OcrReviewCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr-center': {
      id: '/ocr-center'
      path: '/ocr-center'
      fullPath: '/ocr-center'
      preLoaderRoute: typeof OcrCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-generator': {
      id: '/document-generator'
      path: '/document-generator'
      fullPath: '/document-generator'
      preLoaderRoute: typeof DocumentGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-auth-public': {
      id: '/debug-auth-public'
      path: '/debug-auth-public'
      fullPath: '/debug-auth-public'
      preLoaderRoute: typeof DebugAuthPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-v2': {
      id: '/dashboard-v2'
      path: '/dashboard-v2'
      fullPath: '/dashboard-v2'
      preLoaderRoute: typeof DashboardV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-safe': {
      id: '/dashboard-safe'
      path: '/dashboard-safe'
      fullPath: '/dashboard-safe'
      preLoaderRoute: typeof DashboardSafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-portal': {
      id: '/client-portal'
      path: '/client-portal'
      fullPath: '/client-portal'
      preLoaderRoute: typeof ClientPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation-center': {
      id: '/automation-center'
      path: '/automation-center'
      fullPath: '/automation-center'
      preLoaderRoute: typeof AutomationCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-debug-public': {
      id: '/auth-debug-public'
      path: '/auth-debug-public'
      fullPath: '/auth-debug-public'
      preLoaderRoute: typeof AuthDebugPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-debug': {
      id: '/auth-debug'
      path: '/auth-debug'
      fullPath: '/auth-debug'
      preLoaderRoute: typeof AuthDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-center': {
      id: '/ai-center'
      path: '/ai-center'
      fullPath: '/ai-center'
      preLoaderRoute: typeof AiCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/processes/$id': {
      id: '/processes/$id'
      path: '/$id'
      fullPath: '/processes/$id'
      preLoaderRoute: typeof ProcessesIdRouteImport
      parentRoute: typeof ProcessesRoute
    }
    '/debug/system': {
      id: '/debug/system'
      path: '/debug/system'
      fullPath: '/debug/system'
      preLoaderRoute: typeof DebugSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/auth': {
      id: '/debug/auth'
      path: '/debug/auth'
      fullPath: '/debug/auth'
      preLoaderRoute: typeof DebugAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ecosystem': {
      id: '/dashboard/ecosystem'
      path: '/ecosystem'
      fullPath: '/dashboard/ecosystem'
      preLoaderRoute: typeof DashboardEcosystemRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents-base': {
      id: '/dashboard/documents-base'
      path: '/documents-base'
      fullPath: '/dashboard/documents-base'
      preLoaderRoute: typeof DashboardDocumentsBaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/document-center': {
      id: '/dashboard/document-center'
      path: '/document-center'
      fullPath: '/dashboard/document-center'
      preLoaderRoute: typeof DashboardDocumentCenterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deadlines': {
      id: '/dashboard/deadlines'
      path: '/deadlines'
      fullPath: '/dashboard/deadlines'
      preLoaderRoute: typeof DashboardDeadlinesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/compliance-center': {
      id: '/dashboard/compliance-center'
      path: '/compliance-center'
      fullPath: '/dashboard/compliance-center'
      preLoaderRoute: typeof DashboardComplianceCenterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/subscription': {
      id: '/billing/subscription'
      path: '/billing/subscription'
      fullPath: '/billing/subscription'
      preLoaderRoute: typeof BillingSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/failure': {
      id: '/billing/failure'
      path: '/billing/failure'
      fullPath: '/billing/failure'
      preLoaderRoute: typeof BillingFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/operations': {
      id: '/analytics/operations'
      path: '/operations'
      fullPath: '/analytics/operations'
      preLoaderRoute: typeof AnalyticsOperationsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/ocr': {
      id: '/analytics/ocr'
      path: '/ocr'
      fullPath: '/analytics/ocr'
      preLoaderRoute: typeof AnalyticsOcrRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-report': {
      id: '/admin/system-report'
      path: '/system-report'
      fullPath: '/admin/system-report'
      preLoaderRoute: typeof AdminSystemReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/storage': {
      id: '/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AdminStorageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/saas-metrics': {
      id: '/admin/saas-metrics'
      path: '/saas-metrics'
      fullPath: '/admin/saas-metrics'
      preLoaderRoute: typeof AdminSaasMetricsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roadmap': {
      id: '/admin/roadmap'
      path: '/roadmap'
      fullPath: '/admin/roadmap'
      preLoaderRoute: typeof AdminRoadmapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operational-feedback': {
      id: '/admin/operational-feedback'
      path: '/operational-feedback'
      fullPath: '/admin/operational-feedback'
      preLoaderRoute: typeof AdminOperationalFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ocr': {
      id: '/admin/ocr'
      path: '/ocr'
      fullPath: '/admin/ocr'
      preLoaderRoute: typeof AdminOcrRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/global': {
      id: '/admin/global'
      path: '/global'
      fullPath: '/admin/global'
      preLoaderRoute: typeof AdminGlobalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/full-qa-report': {
      id: '/admin/full-qa-report'
      path: '/full-qa-report'
      fullPath: '/admin/full-qa-report'
      preLoaderRoute: typeof AdminFullQaReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/frontend-errors': {
      id: '/admin/frontend-errors'
      path: '/frontend-errors'
      fullPath: '/admin/frontend-errors'
      preLoaderRoute: typeof AdminFrontendErrorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/field-validation-report': {
      id: '/admin/field-validation-report'
      path: '/field-validation-report'
      fullPath: '/admin/field-validation-report'
      preLoaderRoute: typeof AdminFieldValidationReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/executive-overview': {
      id: '/admin/executive-overview'
      path: '/executive-overview'
      fullPath: '/admin/executive-overview'
      preLoaderRoute: typeof AdminExecutiveOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/document-library': {
      id: '/admin/document-library'
      path: '/document-library'
      fullPath: '/admin/document-library'
      preLoaderRoute: typeof AdminDocumentLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commercial': {
      id: '/admin/commercial'
      path: '/commercial'
      fullPath: '/admin/commercial'
      preLoaderRoute: typeof AdminCommercialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automation': {
      id: '/admin/automation'
      path: '/automation'
      fullPath: '/admin/automation'
      preLoaderRoute: typeof AdminAutomationRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAutomationRoute: typeof AdminAutomationRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCommercialRoute: typeof AdminCommercialRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminDocumentLibraryRoute: typeof AdminDocumentLibraryRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminExecutiveOverviewRoute: typeof AdminExecutiveOverviewRoute
  AdminFieldValidationReportRoute: typeof AdminFieldValidationReportRoute
  AdminFrontendErrorsRoute: typeof AdminFrontendErrorsRoute
  AdminFullQaReportRoute: typeof AdminFullQaReportRoute
  AdminGlobalRoute: typeof AdminGlobalRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminOcrRoute: typeof AdminOcrRoute
  AdminOperationalFeedbackRoute: typeof AdminOperationalFeedbackRoute
  AdminRoadmapRoute: typeof AdminRoadmapRoute
  AdminSaasMetricsRoute: typeof AdminSaasMetricsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStorageRoute: typeof AdminStorageRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSystemReportRoute: typeof AdminSystemReportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAutomationRoute: AdminAutomationRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCommercialRoute: AdminCommercialRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminDocumentLibraryRoute: AdminDocumentLibraryRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminExecutiveOverviewRoute: AdminExecutiveOverviewRoute,
  AdminFieldValidationReportRoute: AdminFieldValidationReportRoute,
  AdminFrontendErrorsRoute: AdminFrontendErrorsRoute,
  AdminFullQaReportRoute: AdminFullQaReportRoute,
  AdminGlobalRoute: AdminGlobalRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminOcrRoute: AdminOcrRoute,
  AdminOperationalFeedbackRoute: AdminOperationalFeedbackRoute,
  AdminRoadmapRoute: AdminRoadmapRoute,
  AdminSaasMetricsRoute: AdminSaasMetricsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStorageRoute: AdminStorageRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminSystemReportRoute: AdminSystemReportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AnalyticsRouteChildren {
  AnalyticsOcrRoute: typeof AnalyticsOcrRoute
  AnalyticsOperationsRoute: typeof AnalyticsOperationsRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsOcrRoute: AnalyticsOcrRoute,
  AnalyticsOperationsRoute: AnalyticsOperationsRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardComplianceCenterRoute: typeof DashboardComplianceCenterRoute
  DashboardDeadlinesRoute: typeof DashboardDeadlinesRoute
  DashboardDocumentCenterRoute: typeof DashboardDocumentCenterRoute
  DashboardDocumentsBaseRoute: typeof DashboardDocumentsBaseRoute
  DashboardEcosystemRoute: typeof DashboardEcosystemRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardComplianceCenterRoute: DashboardComplianceCenterRoute,
  DashboardDeadlinesRoute: DashboardDeadlinesRoute,
  DashboardDocumentCenterRoute: DashboardDocumentCenterRoute,
  DashboardDocumentsBaseRoute: DashboardDocumentsBaseRoute,
  DashboardEcosystemRoute: DashboardEcosystemRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProcessesRouteChildren {
  ProcessesIdRoute: typeof ProcessesIdRoute
}

const ProcessesRouteChildren: ProcessesRouteChildren = {
  ProcessesIdRoute: ProcessesIdRoute,
}

const ProcessesRouteWithChildren = ProcessesRoute._addFileChildren(
  ProcessesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiCenterRoute: AiCenterRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  AuthDebugRoute: AuthDebugRoute,
  AuthDebugPublicRoute: AuthDebugPublicRoute,
  AutomationRoute: AutomationRoute,
  AutomationCenterRoute: AutomationCenterRoute,
  CalendarRoute: CalendarRoute,
  ChangelogRoute: ChangelogRoute,
  ClientPortalRoute: ClientPortalRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DashboardSafeRoute: DashboardSafeRoute,
  DashboardV2Route: DashboardV2Route,
  DebugAuthPublicRoute: DebugAuthPublicRoute,
  DemoRoute: DemoRoute,
  DocumentGeneratorRoute: DocumentGeneratorRoute,
  DocumentsRoute: DocumentsRoute,
  GettingStartedRoute: GettingStartedRoute,
  HomeRoute: HomeRoute,
  LogsRoute: LogsRoute,
  OcrCenterRoute: OcrCenterRoute,
  OcrReviewCenterRoute: OcrReviewCenterRoute,
  OnboardingRoute: OnboardingRoute,
  OperationsCenterRoute: OperationsCenterRoute,
  PerformanceCenterRoute: PerformanceCenterRoute,
  PlansRoute: PlansRoute,
  ProcessesRoute: ProcessesRouteWithChildren,
  SalesCenterRoute: SalesCenterRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  SupportRoute: SupportRoute,
  SystemMonitorRoute: SystemMonitorRoute,
  VesselsRoute: VesselsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  BillingFailureRoute: BillingFailureRoute,
  BillingSubscriptionRoute: BillingSubscriptionRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  DebugAuthRoute: DebugAuthRoute,
  DebugSystemRoute: DebugSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
