/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VesselsRouteImport } from './routes/vessels'
import { Route as SystemMonitorRouteImport } from './routes/system-monitor'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as OperationsCenterRouteImport } from './routes/operations-center'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OcrReviewCenterRouteImport } from './routes/ocr-review-center'
import { Route as OcrCenterRouteImport } from './routes/ocr-center'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DocumentGeneratorRouteImport } from './routes/document-generator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AutomationCenterRouteImport } from './routes/automation-center'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiCenterRouteImport } from './routes/ai-center'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProcessesIdRouteImport } from './routes/processes.$id'
import { Route as DebugSystemRouteImport } from './routes/debug.system'
import { Route as DashboardDocumentsBaseRouteImport } from './routes/dashboard/documents-base'
import { Route as DashboardComplianceCenterRouteImport } from './routes/dashboard/compliance-center'
import { Route as BillingSuccessRouteImport } from './routes/billing.success'
import { Route as BillingSubscriptionRouteImport } from './routes/billing.subscription'
import { Route as BillingFailureRouteImport } from './routes/billing.failure'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AnalyticsOperationsRouteImport } from './routes/analytics.operations'
import { Route as AnalyticsOcrRouteImport } from './routes/analytics.ocr'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSystemReportRouteImport } from './routes/admin/system-report'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminDocumentLibraryRouteImport } from './routes/admin/document-library'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as AdminCommercialRouteImport } from './routes/admin/commercial'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as AdminAutomationRouteImport } from './routes/admin/automation'

const VesselsRoute = VesselsRouteImport.update({
  id: '/vessels',
  path: '/vessels',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemMonitorRoute = SystemMonitorRouteImport.update({
  id: '/system-monitor',
  path: '/system-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsCenterRoute = OperationsCenterRouteImport.update({
  id: '/operations-center',
  path: '/operations-center',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrReviewCenterRoute = OcrReviewCenterRouteImport.update({
  id: '/ocr-review-center',
  path: '/ocr-review-center',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrCenterRoute = OcrCenterRouteImport.update({
  id: '/ocr-center',
  path: '/ocr-center',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentGeneratorRoute = DocumentGeneratorRouteImport.update({
  id: '/document-generator',
  path: '/document-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationCenterRoute = AutomationCenterRouteImport.update({
  id: '/automation-center',
  path: '/automation-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCenterRoute = AiCenterRouteImport.update({
  id: '/ai-center',
  path: '/ai-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProcessesIdRoute = ProcessesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProcessesRoute,
} as any)
const DebugSystemRoute = DebugSystemRouteImport.update({
  id: '/debug/system',
  path: '/debug/system',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDocumentsBaseRoute = DashboardDocumentsBaseRouteImport.update({
  id: '/documents-base',
  path: '/documents-base',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplianceCenterRoute =
  DashboardComplianceCenterRouteImport.update({
    id: '/compliance-center',
    path: '/compliance-center',
    getParentRoute: () => DashboardRoute,
  } as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSubscriptionRoute = BillingSubscriptionRouteImport.update({
  id: '/billing/subscription',
  path: '/billing/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingFailureRoute = BillingFailureRouteImport.update({
  id: '/billing/failure',
  path: '/billing/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsOperationsRoute = AnalyticsOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsOcrRoute = AnalyticsOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemReportRoute = AdminSystemReportRouteImport.update({
  id: '/system-report',
  path: '/system-report',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentLibraryRoute = AdminDocumentLibraryRouteImport.update({
  id: '/document-library',
  path: '/document-library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommercialRoute = AdminCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomationRoute = AdminAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-center': typeof AiCenterRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/automation': typeof AutomationRoute
  '/automation-center': typeof AutomationCenterRoute
  '/calendar': typeof CalendarRoute
  '/changelog': typeof ChangelogRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/document-generator': typeof DocumentGeneratorRoute
  '/documents': typeof DocumentsRoute
  '/home': typeof HomeRoute
  '/ocr-center': typeof OcrCenterRoute
  '/ocr-review-center': typeof OcrReviewCenterRoute
  '/onboarding': typeof OnboardingRoute
  '/operations-center': typeof OperationsCenterRoute
  '/plans': typeof PlansRoute
  '/processes': typeof ProcessesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/vessels': typeof VesselsRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/commercial': typeof AdminCommercialRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/document-library': typeof AdminDocumentLibraryRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-report': typeof AdminSystemReportRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/ocr': typeof AnalyticsOcrRoute
  '/analytics/operations': typeof AnalyticsOperationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/billing/failure': typeof BillingFailureRoute
  '/billing/subscription': typeof BillingSubscriptionRoute
  '/billing/success': typeof BillingSuccessRoute
  '/dashboard/compliance-center': typeof DashboardComplianceCenterRoute
  '/dashboard/documents-base': typeof DashboardDocumentsBaseRoute
  '/debug/system': typeof DebugSystemRoute
  '/processes/$id': typeof ProcessesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-center': typeof AiCenterRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/automation': typeof AutomationRoute
  '/automation-center': typeof AutomationCenterRoute
  '/calendar': typeof CalendarRoute
  '/changelog': typeof ChangelogRoute
  '/customers': typeof CustomersRoute
  '/document-generator': typeof DocumentGeneratorRoute
  '/documents': typeof DocumentsRoute
  '/home': typeof HomeRoute
  '/ocr-center': typeof OcrCenterRoute
  '/ocr-review-center': typeof OcrReviewCenterRoute
  '/onboarding': typeof OnboardingRoute
  '/operations-center': typeof OperationsCenterRoute
  '/plans': typeof PlansRoute
  '/processes': typeof ProcessesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/vessels': typeof VesselsRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/commercial': typeof AdminCommercialRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/document-library': typeof AdminDocumentLibraryRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-report': typeof AdminSystemReportRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/ocr': typeof AnalyticsOcrRoute
  '/analytics/operations': typeof AnalyticsOperationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/billing/failure': typeof BillingFailureRoute
  '/billing/subscription': typeof BillingSubscriptionRoute
  '/billing/success': typeof BillingSuccessRoute
  '/dashboard/compliance-center': typeof DashboardComplianceCenterRoute
  '/dashboard/documents-base': typeof DashboardDocumentsBaseRoute
  '/debug/system': typeof DebugSystemRoute
  '/processes/$id': typeof ProcessesIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-center': typeof AiCenterRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/automation': typeof AutomationRoute
  '/automation-center': typeof AutomationCenterRoute
  '/calendar': typeof CalendarRoute
  '/changelog': typeof ChangelogRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/document-generator': typeof DocumentGeneratorRoute
  '/documents': typeof DocumentsRoute
  '/home': typeof HomeRoute
  '/ocr-center': typeof OcrCenterRoute
  '/ocr-review-center': typeof OcrReviewCenterRoute
  '/onboarding': typeof OnboardingRoute
  '/operations-center': typeof OperationsCenterRoute
  '/plans': typeof PlansRoute
  '/processes': typeof ProcessesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/system-monitor': typeof SystemMonitorRoute
  '/vessels': typeof VesselsRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/commercial': typeof AdminCommercialRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/document-library': typeof AdminDocumentLibraryRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-report': typeof AdminSystemReportRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/ocr': typeof AnalyticsOcrRoute
  '/analytics/operations': typeof AnalyticsOperationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/billing/failure': typeof BillingFailureRoute
  '/billing/subscription': typeof BillingSubscriptionRoute
  '/billing/success': typeof BillingSuccessRoute
  '/dashboard/compliance-center': typeof DashboardComplianceCenterRoute
  '/dashboard/documents-base': typeof DashboardDocumentsBaseRoute
  '/debug/system': typeof DebugSystemRoute
  '/processes/$id': typeof ProcessesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-center'
    | '/analytics'
    | '/automation'
    | '/automation-center'
    | '/calendar'
    | '/changelog'
    | '/customers'
    | '/dashboard'
    | '/document-generator'
    | '/documents'
    | '/home'
    | '/ocr-center'
    | '/ocr-review-center'
    | '/onboarding'
    | '/operations-center'
    | '/plans'
    | '/processes'
    | '/settings'
    | '/status'
    | '/support'
    | '/system-monitor'
    | '/vessels'
    | '/admin/automation'
    | '/admin/billing'
    | '/admin/commercial'
    | '/admin/companies'
    | '/admin/document-library'
    | '/admin/documents'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin/system-report'
    | '/admin/users'
    | '/analytics/ocr'
    | '/analytics/operations'
    | '/auth/login'
    | '/auth/signup'
    | '/billing/failure'
    | '/billing/subscription'
    | '/billing/success'
    | '/dashboard/compliance-center'
    | '/dashboard/documents-base'
    | '/debug/system'
    | '/processes/$id'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-center'
    | '/analytics'
    | '/automation'
    | '/automation-center'
    | '/calendar'
    | '/changelog'
    | '/customers'
    | '/document-generator'
    | '/documents'
    | '/home'
    | '/ocr-center'
    | '/ocr-review-center'
    | '/onboarding'
    | '/operations-center'
    | '/plans'
    | '/processes'
    | '/settings'
    | '/status'
    | '/support'
    | '/system-monitor'
    | '/vessels'
    | '/admin/automation'
    | '/admin/billing'
    | '/admin/commercial'
    | '/admin/companies'
    | '/admin/document-library'
    | '/admin/documents'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin/system-report'
    | '/admin/users'
    | '/analytics/ocr'
    | '/analytics/operations'
    | '/auth/login'
    | '/auth/signup'
    | '/billing/failure'
    | '/billing/subscription'
    | '/billing/success'
    | '/dashboard/compliance-center'
    | '/dashboard/documents-base'
    | '/debug/system'
    | '/processes/$id'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-center'
    | '/analytics'
    | '/automation'
    | '/automation-center'
    | '/calendar'
    | '/changelog'
    | '/customers'
    | '/dashboard'
    | '/document-generator'
    | '/documents'
    | '/home'
    | '/ocr-center'
    | '/ocr-review-center'
    | '/onboarding'
    | '/operations-center'
    | '/plans'
    | '/processes'
    | '/settings'
    | '/status'
    | '/support'
    | '/system-monitor'
    | '/vessels'
    | '/admin/automation'
    | '/admin/billing'
    | '/admin/commercial'
    | '/admin/companies'
    | '/admin/document-library'
    | '/admin/documents'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin/system-report'
    | '/admin/users'
    | '/analytics/ocr'
    | '/analytics/operations'
    | '/auth/login'
    | '/auth/signup'
    | '/billing/failure'
    | '/billing/subscription'
    | '/billing/success'
    | '/dashboard/compliance-center'
    | '/dashboard/documents-base'
    | '/debug/system'
    | '/processes/$id'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiCenterRoute: typeof AiCenterRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  AutomationRoute: typeof AutomationRoute
  AutomationCenterRoute: typeof AutomationCenterRoute
  CalendarRoute: typeof CalendarRoute
  ChangelogRoute: typeof ChangelogRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocumentGeneratorRoute: typeof DocumentGeneratorRoute
  DocumentsRoute: typeof DocumentsRoute
  HomeRoute: typeof HomeRoute
  OcrCenterRoute: typeof OcrCenterRoute
  OcrReviewCenterRoute: typeof OcrReviewCenterRoute
  OnboardingRoute: typeof OnboardingRoute
  OperationsCenterRoute: typeof OperationsCenterRoute
  PlansRoute: typeof PlansRoute
  ProcessesRoute: typeof ProcessesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  SupportRoute: typeof SupportRoute
  SystemMonitorRoute: typeof SystemMonitorRoute
  VesselsRoute: typeof VesselsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BillingFailureRoute: typeof BillingFailureRoute
  BillingSubscriptionRoute: typeof BillingSubscriptionRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  DebugSystemRoute: typeof DebugSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vessels': {
      id: '/vessels'
      path: '/vessels'
      fullPath: '/vessels'
      preLoaderRoute: typeof VesselsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-monitor': {
      id: '/system-monitor'
      path: '/system-monitor'
      fullPath: '/system-monitor'
      preLoaderRoute: typeof SystemMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations-center': {
      id: '/operations-center'
      path: '/operations-center'
      fullPath: '/operations-center'
      preLoaderRoute: typeof OperationsCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr-review-center': {
      id: '/ocr-review-center'
      path: '/ocr-review-center'
      fullPath: '/ocr-review-center'
      preLoaderRoute: typeof OcrReviewCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr-center': {
      id: '/ocr-center'
      path: '/ocr-center'
      fullPath: '/ocr-center'
      preLoaderRoute: typeof OcrCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-generator': {
      id: '/document-generator'
      path: '/document-generator'
      fullPath: '/document-generator'
      preLoaderRoute: typeof DocumentGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation-center': {
      id: '/automation-center'
      path: '/automation-center'
      fullPath: '/automation-center'
      preLoaderRoute: typeof AutomationCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-center': {
      id: '/ai-center'
      path: '/ai-center'
      fullPath: '/ai-center'
      preLoaderRoute: typeof AiCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/processes/$id': {
      id: '/processes/$id'
      path: '/$id'
      fullPath: '/processes/$id'
      preLoaderRoute: typeof ProcessesIdRouteImport
      parentRoute: typeof ProcessesRoute
    }
    '/debug/system': {
      id: '/debug/system'
      path: '/debug/system'
      fullPath: '/debug/system'
      preLoaderRoute: typeof DebugSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/documents-base': {
      id: '/dashboard/documents-base'
      path: '/documents-base'
      fullPath: '/dashboard/documents-base'
      preLoaderRoute: typeof DashboardDocumentsBaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/compliance-center': {
      id: '/dashboard/compliance-center'
      path: '/compliance-center'
      fullPath: '/dashboard/compliance-center'
      preLoaderRoute: typeof DashboardComplianceCenterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/subscription': {
      id: '/billing/subscription'
      path: '/billing/subscription'
      fullPath: '/billing/subscription'
      preLoaderRoute: typeof BillingSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/failure': {
      id: '/billing/failure'
      path: '/billing/failure'
      fullPath: '/billing/failure'
      preLoaderRoute: typeof BillingFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/operations': {
      id: '/analytics/operations'
      path: '/operations'
      fullPath: '/analytics/operations'
      preLoaderRoute: typeof AnalyticsOperationsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/ocr': {
      id: '/analytics/ocr'
      path: '/ocr'
      fullPath: '/analytics/ocr'
      preLoaderRoute: typeof AnalyticsOcrRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-report': {
      id: '/admin/system-report'
      path: '/system-report'
      fullPath: '/admin/system-report'
      preLoaderRoute: typeof AdminSystemReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/document-library': {
      id: '/admin/document-library'
      path: '/document-library'
      fullPath: '/admin/document-library'
      preLoaderRoute: typeof AdminDocumentLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commercial': {
      id: '/admin/commercial'
      path: '/commercial'
      fullPath: '/admin/commercial'
      preLoaderRoute: typeof AdminCommercialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automation': {
      id: '/admin/automation'
      path: '/automation'
      fullPath: '/admin/automation'
      preLoaderRoute: typeof AdminAutomationRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAutomationRoute: typeof AdminAutomationRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCommercialRoute: typeof AdminCommercialRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminDocumentLibraryRoute: typeof AdminDocumentLibraryRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSystemReportRoute: typeof AdminSystemReportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAutomationRoute: AdminAutomationRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCommercialRoute: AdminCommercialRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminDocumentLibraryRoute: AdminDocumentLibraryRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSystemReportRoute: AdminSystemReportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AnalyticsRouteChildren {
  AnalyticsOcrRoute: typeof AnalyticsOcrRoute
  AnalyticsOperationsRoute: typeof AnalyticsOperationsRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsOcrRoute: AnalyticsOcrRoute,
  AnalyticsOperationsRoute: AnalyticsOperationsRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardComplianceCenterRoute: typeof DashboardComplianceCenterRoute
  DashboardDocumentsBaseRoute: typeof DashboardDocumentsBaseRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardComplianceCenterRoute: DashboardComplianceCenterRoute,
  DashboardDocumentsBaseRoute: DashboardDocumentsBaseRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProcessesRouteChildren {
  ProcessesIdRoute: typeof ProcessesIdRoute
}

const ProcessesRouteChildren: ProcessesRouteChildren = {
  ProcessesIdRoute: ProcessesIdRoute,
}

const ProcessesRouteWithChildren = ProcessesRoute._addFileChildren(
  ProcessesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiCenterRoute: AiCenterRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  AutomationRoute: AutomationRoute,
  AutomationCenterRoute: AutomationCenterRoute,
  CalendarRoute: CalendarRoute,
  ChangelogRoute: ChangelogRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocumentGeneratorRoute: DocumentGeneratorRoute,
  DocumentsRoute: DocumentsRoute,
  HomeRoute: HomeRoute,
  OcrCenterRoute: OcrCenterRoute,
  OcrReviewCenterRoute: OcrReviewCenterRoute,
  OnboardingRoute: OnboardingRoute,
  OperationsCenterRoute: OperationsCenterRoute,
  PlansRoute: PlansRoute,
  ProcessesRoute: ProcessesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  SupportRoute: SupportRoute,
  SystemMonitorRoute: SystemMonitorRoute,
  VesselsRoute: VesselsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  BillingFailureRoute: BillingFailureRoute,
  BillingSubscriptionRoute: BillingSubscriptionRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  DebugSystemRoute: DebugSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
