ALTER TABLE public.document_fields 
ADD COLUMN IF NOT EXISTS width DOUBLE PRECISION DEFAULT 100,
ADD COLUMN IF NOT EXISTS height DOUBLE PRECISION DEFAULT 20,
ADD COLUMN IF NOT EXISTS font_size INTEGER DEFAULT 10,
ADD COLUMN IF NOT EXISTS field_options JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS alignment TEXT DEFAULT 'left';
